### ISSUE TITLE
get_child_collections fails with 'Collection parent value is not a a valid integer'

### ISSUE THREAD

**Issue by ckhan** [PBorocz/raindrop-io-py#19]
Hello Peter - I know you said you're not maintaining this any more, but thought I'd file just in case you have bandwidth to take a look.
The[ first API example on the project home](https://github.com/PBorocz/raindrop-io-py?tab=readme-ov-file#display-all-collections-and-unsorted-bookmarks) page ("Display All Collections") fails for me with this stack trace:

```
Traceback (most recent call last):
  File "/home/user/try/raindrop/raindrop.py", line 17, in <module>
    for collection in Collection.get_collections(api):
  File "/home/user/usr/pylin/lib/python3.10/site-packages/raindropiopy/models.py", line 279, in get_collections
    return cls.get_root_collections(api) + cls.get_child_collections(api)
  File "/home/user/usr/pylin/lib/python3.10/site-packages/raindropiopy/models.py", line 266, in get_child_collections
    return [cls(**item) for item in items]
  File "/home/user/usr/pylin/lib/python3.10/site-packages/raindropiopy/models.py", line 266, in <listcomp>
    return [cls(**item) for item in items]
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Collection
parent
  value is not a valid integer (type=type_error.integer)
```

I think this because the 'parent' key in a child collection is not just an integer, it's
a dict that looks like this :

`    "parent":{"$ref":"collections","$id":37277248}`

which is why I think it's failing the pydantic validation.
I'm on Ubuntu 22.04; Python 3.10.12, and raindrop-io-py 0.1.2

**Comment by PBorocz** [comment]
I think I ran into another few places where this occurs (and fixed) but probably didn't expect this one!.

I'll setup a new Raindrop account and fix/test over the coming week (it's too embarrassing to leave out there!)

Thanks!

**Comment by PBorocz** [comment]
Looked into this today and can confirm that it's FIXED as of [v0.2.0 from 2023-12-12](https://github.com/PBorocz/raindrop-io-py?tab=readme-ov-file#v020---2023-12-12):

> - FIXED: Inability to correctly handle "sub" or child collections. We now correctly unpack 'parent' references on querying child collections...(ht to @limaceous-bushwhacker in [Issue 12](https://github.com/PBorocz/raindrop-io-py/issues/12).

Looking at your report, version 0.1.2 definitely wouldn't have handled it. Upgrade and you should be good!

**Comment by ckhan** [comment]
Thank you so much for looking into this.
Confirmed that the the issue is fixed when I upgrade to 0.2.5

One thing that is surprising to me: I did not realize I was on an old release -- I see now it's because starting with 0.1.3, the package explicitly requires Python 3.11+ ; even though the description for 0.1.3 and indeed for the head release say Python 3.10+ is required. Because I was on 3.10, pypi installed 0.1.2, which of course, is too old.

What would be really great is if this package would work on 3.10 (upgrading my whole project to 3.12 has pulled in a whole new set of dependencies and problems that I can't address just yet).

If that's not possible -- maybe remove/deprecate the 3.10 versions, since that version of the package isn't functional, even with Python 3.10. 

And finally if re-qualifying 3.10 isn't possible, may I suggest docs should also be updated to reflect the package requirements.

Thanks again!
-ck

**Comment by PBorocz** [comment]
TTBOMK, there was only one code change to "back" support 3.10 (and that was only in the test suite). I started to use NOX to run tests against the most recent 3.10, 3.11 and 3.12 releases. `pyproject.toml` now reflects 3.10+ for python (and is back to being consistent with the "badge" ;-)

Thus, I *THINK* this might work for you..I say "think" only because I haven't "down-revved" required packages to the minimal necessary to run under 3.10, thus, these stay at the reasonably current versions (some of which need to based on CVE's encountered recently).

Thanks for the feedback, got me to learn more tools!

**Comment by ckhan** [comment]
Thank you, confirmed that this does work correctly on Python 3.10.
