### ISSUE TITLE
No Results From Search

### ISSUE THREAD

**Issue by mko237** [PBorocz/raindrop-io-py#4]
Hi,

I found this package from a comment on this same [issue](https://github.com/atsuoishimoto/python-raindropio/issues/5), reported over on the original python-raindropio package.

 I switched to this package hoping it would help but seems that it has the same problem. 

If you see [my comment](https://github.com/atsuoishimoto/python-raindropio/issues/5#issuecomment-1575534537) on the original issue, you should be able to apply the same fix to the [line here]( https://github.com/PBorocz/raindrop-io-py/blob/f1bfd85c859328be34f0ba806f8b16c2503e68a9/raindropiopy/models.py#L920)

Thanks, hope this helps.

**Comment by PBorocz** [comment]
Thanks @mko237! 
Indeed it would be here as the core API code was essentially cloned from Atsuo's package. 

Although I can't confirm through WaybackMachine (but I'm positive search worked correctly before), it seems like the raindropio API doesn't take a JSON-encoded search parameter anymore, instead just the same string we'd use through their UI ("searchMe", "#MyTag" etc.).

Thus, I've simplified the API call to Raindrop.search and confirmed that wildcard searches work (either against a single or all collections).

Thanks for the feedback!
